CREATE TABLE Player(
PLAYER_ID SERIAL,
TEAM_ID   INT   NOT NULL,
UNIFORM_NUM   INT   NOT NULL,
FIRST_NAME   VARCHAR(128)  NOT NULL,
LAST_NAME    VARCHAR(128)  NOT NULL,
MPG    INT DEFAULT 0,
PPG    INT DEFAULT 0,
RPG    INT DEFAULT 0,
APG    INT DEFAULT 0,
SPG    NUMERIC(2,1) DEFAULT 0,
BPG    NUMERIC(2,1) DEFAULT 0,
PRIMARY KEY (PLAYER_ID)
);