CREATE TABLE COLOR(
COLOR_ID SERIAL,
NAME VARCHAR(128),
PRIMARY KEY (COLOR_ID)
);

CREATE TABLE STATE(
STATE_ID SERIAL, 
NAME VARCHAR(128),
PRIMARY KEY (STATE_ID)
);

CREATE TABLE TEAM(
TEAM_ID SERIAL,
NAME VARCHAR(128),
STATE_ID INT NOT NULL,
COLOR_ID  INT NOT NULL,
WINS INT NOT NULL,
LOSSES INT NOT NULL,
PRIMARY KEY (TEAM_ID),
FOREIGN KEY (STATE_ID) REFERENCES STATE(STATE_ID) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (COLOR_ID) REFERENCES COLOR(COLOR_ID) ON DELETE SET NULL ON UPDATE CASCADE
);



CREATE TABLE PLAYER(
PLAYER_ID SERIAL,
TEAM_ID  INT NOT NULL,
UNIFORM_NUM  INT NOT NULL,
FIRST_NAME VARCHAR(128) NOT NULL,
LAST_NAME  VARCHAR(128) NOT NULL,
MPG  INT DEFAULT 0,
PPG  INT DEFAULT 0,
RPG  INT DEFAULT 0,
APG  INT DEFAULT 0,
SPG  NUMERIC(2,1) DEFAULT 0,
BPG  NUMERIC(2,1) DEFAULT 0,
PRIMARY KEY (PLAYER_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE SET NULL ON UPDATE CASCADE
);